This an example architecture project for a full jee6 project, its configured with:
-Maven;
-JSF2;
-Richafaces;
-Unitils:
 -Full support for functional with integration test;
 -Selenium framework for web functional tests;
 -DBunit Framework for integration test;s
 -Mockito for mocking simple tests.
-It has a little webservice;
-Full support for richfaces pagination by dataset;
-Basics query with Critiria API.
